import type { RagTrace } from "@/types/rag";

export const sampleRagTrace: RagTrace = {
  question:
    "Which drugs had the biggest Medicare Part D spending increase, and what public evidence explains it?",
  route: "HYBRID_SQL_RAG",
  confidence: "High",
  nodes: [
    {
      id: "question",
      type: "question",
      label: "User Question",
      description:
        "The user asked for a spending trend and supporting public evidence.",
      status: "complete",
      details: [
        "Original question: Which drugs had the biggest Medicare Part D spending increase?",
        "This needs exact numbers plus source-grounded explanation.",
      ],
    },
    {
      id: "router",
      type: "router",
      label: "Router Agent",
      description: "Classified the question as HYBRID_SQL_RAG.",
      status: "complete",
      details: [
        "SQL is needed for exact spending calculations.",
        "RAG is needed for dataset meaning, drug context, and limitations.",
      ],
    },
    {
      id: "entity",
      type: "entity",
      label: "Entity Extractor",
      description: "Detected the main entities and metrics.",
      status: "complete",
      details: [
        "Metric: Medicare Part D spending increase",
        "Dataset: CMS Medicare Part D Spending by Drug",
        "Evidence source: CMS/openFDA knowledge base",
      ],
    },
    {
      id: "sql-agent",
      type: "sql",
      label: "SQL Agent",
      description: "Prepared a safe read-only SQL query.",
      status: "complete",
      details: [
        "Only SELECT queries are allowed.",
        "The query compares spending across years.",
        "The result supports numeric claims only.",
      ],
    },
    {
      id: "cms-table",
      type: "table",
      label: "CMS Spending Table",
      description: "Structured table used for exact spending results.",
      status: "used",
      details: [
        "Table: cms_part_d_spending",
        "Fields: brand_name, generic_name, manufacturer, year, total_spending",
        "Purpose: identify top spending increases.",
      ],
    },
    {
      id: "sql-result",
      type: "result",
      label: "SQL Result",
      description: "Returned ranked drug spending increases.",
      status: "used",
      score: 0.96,
      details: [
        "Used to support the final numeric ranking.",
        "No numbers should be invented by the LLM.",
        "Final answer must cite this result for spending claims.",
      ],
    },
    {
      id: "rag-retriever",
      type: "retriever",
      label: "RAG Retriever",
      description: "Searched the knowledge base for supporting context.",
      status: "complete",
      details: [
        "Used vector search and keyword matching.",
        "Looked for CMS methodology and FDA drug context.",
        "Retrieved candidate source chunks.",
      ],
    },
    {
      id: "cms-methodology",
      type: "chunk",
      label: "CMS Methodology Chunk",
      description: "Explains what the spending metric means.",
      status: "used",
      score: 0.91,
      details: [
        "Supports the meaning of Medicare Part D spending.",
        "Clarifies that this is public Medicare spending, not internal revenue.",
      ],
    },
    {
      id: "fda-label",
      type: "chunk",
      label: "FDA Label Chunk",
      description: "Provides public drug/product context.",
      status: "used",
      score: 0.87,
      details: [
        "Supports drug indication or product context.",
        "Does not explain private sales performance.",
      ],
    },
    {
      id: "rejected-private-deal",
      type: "chunk",
      label: "Private Deal Claim",
      description: "Rejected because public data cannot prove private deal loss.",
      status: "rejected",
      score: 0.22,
      details: [
        "No internal CRM/deal table exists.",
        "No sales rep or private discount evidence exists.",
        "The answer must include a data limitation.",
      ],
    },
    {
      id: "verifier",
      type: "verifier",
      label: "Grounding Verifier",
      description: "Checked whether claims are supported.",
      status: "complete",
      details: [
        "Numeric claims must come from SQL results.",
        "Explanation claims must come from retrieved source chunks.",
        "Private deal-loss claims must be refused or qualified.",
      ],
    },
    {
      id: "answer",
      type: "answer",
      label: "Final Answer",
      description: "Generated a grounded answer with limitations.",
      status: "complete",
      details: [
        "Includes direct answer.",
        "Includes citations.",
        "Includes confidence score.",
        "Includes public-data limitation.",
      ],
    },
  ],
  edges: [
    {
      id: "e-question-router",
      source: "question",
      target: "router",
      label: "classify intent",
    },
    {
      id: "e-router-entity",
      source: "router",
      target: "entity",
      label: "extract entities",
    },
    {
      id: "e-entity-sql",
      source: "entity",
      target: "sql-agent",
      label: "needs exact numbers",
    },
    {
      id: "e-sql-table",
      source: "sql-agent",
      target: "cms-table",
      label: "query spending data",
    },
    {
      id: "e-table-result",
      source: "cms-table",
      target: "sql-result",
      label: "returns ranking",
    },
    {
      id: "e-entity-rag",
      source: "entity",
      target: "rag-retriever",
      label: "needs evidence",
    },
    {
      id: "e-rag-cms",
      source: "rag-retriever",
      target: "cms-methodology",
      label: "retrieved",
    },
    {
      id: "e-rag-fda",
      source: "rag-retriever",
      target: "fda-label",
      label: "retrieved",
    },
    {
      id: "e-rag-rejected",
      source: "rag-retriever",
      target: "rejected-private-deal",
      label: "rejected",
    },
    {
      id: "e-result-verifier",
      source: "sql-result",
      target: "verifier",
      label: "supports numbers",
    },
    {
      id: "e-cms-verifier",
      source: "cms-methodology",
      target: "verifier",
      label: "supports metric meaning",
    },
    {
      id: "e-fda-verifier",
      source: "fda-label",
      target: "verifier",
      label: "supports product context",
    },
    {
      id: "e-rejected-verifier",
      source: "rejected-private-deal",
      target: "verifier",
      label: "blocked unsupported claim",
    },
    {
      id: "e-verifier-answer",
      source: "verifier",
      target: "answer",
      label: "approved grounded answer",
    },
  ],
};